l_state: g100d_highdim
#Example 8: High-dimensional highly nonlinear problem
# Ref. (HMCMC High Dim, Prof. Kostas, pag. 21)
#PF_ref = 3.40E-5

active_samples: 5
active_epochs: 51   #maybe 51

passive_samples: 200
training_epochs: 1000
hidden_sizes: 50
hidden_layers: 1
learning_rate: 0.01  #maybe 0.01
batch_size: 64    #maybe 8

args:
  n_ensembles: 5

# --- reliability estimation options ---
mcs_samples: 1000000
evaluate: False #evaluate lstate over MC population for active learning