l_state: g2d_himmelblau
#Example 4: The Himmelblau Function Ref. (HMCMC High Dim, Prof. Kostas
#Ref. PF=1.65E-4

# --- reliability estimation options ---
mcs_samples: 1000000
evaluate: False #evaluate lstate over MC population for active learning